# skaffold.yaml
apiVersion: skaffold/v4beta7 # 或更新的稳定版本
kind: Config
metadata:
  name: feishu-notification-skaffold

# 由于镜像是通过 Cloud Build 构建并由 'gcloud deploy releases create --images' 传递的，
# 'build' 部分可以省略或留空，Skaffold 将专注于部署。
# build:
#   artifacts: [] # 或者完全省略 build 部分

manifests:
  # 'rawYaml' 用于直接指定 Kubernetes YAML 文件。
  # 如果您将所有 K8s 配置合并到一个文件 (例如 k8s/kubernetes.yaml):
  # rawYaml:
  #  - k8s/kubernetes.yaml
  # 如果您有多个独立的 YAML 文件在 k8s/ 目录下:
  rawYaml:
    - k8s/deployment.yaml
    - k8s/service.yaml
    # - k8s/configmap.yaml # 如果有其他文件

# 'deploy.kubectl' 告诉 Skaffold 使用 kubectl 来应用这些清单。
# 空的 {} 表示使用默认的 kubectl 部署行为。
deploy:
  kubectl: {}
